local MACRO = {}

MACRO.INPUT_LAYER = 30

MACRO.HIDED_LAYER = 2
MACRO.HIDED_LAYER_SIZE = 16

MACRO.OUTPUT_LAYER = 2

MACRO.EPOCH = 50
MACRO.EPOCH_INDEX = 0
MACRO.LINE_READ = 0

MACRO.LEARNING_RATE = 0.005

MACRO.BETA1 = 0.9
MACRO.BETA2 = 0.999
MACRO.EPSILON = 1e-8

MACRO.BATCH_SIZE = 16

MACRO.RELOAD_DATASET = false
MACRO.TRAIN = false

MACRO.MODEL_NAME = "../b1.lua"
MACRO.MODEL_USED = "../b1.lua"

MACRO.PREDICT = nil

return MACRO
