local MACRO = {}

MACRO.INPUT_LAYER = 30

MACRO.HIDED_LAYER = 2
MACRO.HIDED_LAYER_SIZE = 16

MACRO.OUTPUT_LAYER = 2

MACRO.EPOCH = 200
MACRO.EPOCH_INDEX = 0
MACRO.LINE_READ = 0

MACRO.LEARNING_RATE = 0.005

MACRO.BETA1 = 0.9
MACRO.BETA2 = 0.999
MACRO.EPSILON = 1e-8

MACRO.BATCH_SIZE = 32

MACRO.RELOAD_DATASET = false
MACRO.SPLIT_PERCENT = 0.80
MACRO.TRAIN = false
MACRO.EARLY_STOPPING = -1

MACRO.MODEL_NAME = "../MODEL_"..MACRO.HIDED_LAYER.."L_"..MACRO.HIDED_LAYER_SIZE.."LS_"..MACRO.LEARNING_RATE.."LR_"..MACRO.EPOCH.."E".."_B"..MACRO.BATCH_SIZE..".lua"
MACRO.MODEL_USED = "../MODEL_2L_16LS_0.005LR_200E_B32.lua"
MACRO.MIN_MAX_USED = "../min_max.lua"

MACRO.PREDICT = nil
MACRO.FORCE_NORMALIZE = false
MACRO.NORMALIZE_PREDICTION = false

return MACRO
